export const mlMetadata = {
  'chance-events': {
    title: 'Chance Events - Probability Visualization',
    description:
      'Explore probability fundamentals with interactive coin flips and dice rolls. Visualize how random events converge to theoretical probabilities through the Law of Large Numbers.',
    keywords: [
      'chance events',
      'probability',
      'random events',
      'coin flip',
      'dice roll',
      'law of large numbers',
      'probability theory',
      'statistics',
      'probability visualization',
      'machine learning mathematics',
    ],
    ogImage: '/og/og-ml-chance-events.png',
  },
  expectation: {
    title: 'Expected Value (E[X]) - Probability Theory',
    description:
      'Master expected value through interactive dice rolling. Watch running mean converge to E[X] and explore probability-weighted averages with customizable distributions.',
    keywords: [
      'expected value',
      'expectation',
      'probability weighted average',
      'law of large numbers',
      'running mean',
      'probability distribution',
      'statistics',
      'biased die',
      'fair die',
      'convergence',
      'machine learning mathematics',
    ],
    ogImage: '/og/og-ml-expectation.png',
  },
  variance: {
    title: 'Variance - Statistical Spread Measurement',
    description:
      'Understand variance through card drawing simulations. Visualize how variance measures distribution spread and watch running variance converge to theoretical values.',
    keywords: [
      'variance',
      'statistical spread',
      'squared differences',
      'distribution spread',
      'law of large numbers',
      'running variance',
      'probability theory',
      'statistics',
      'standard deviation',
      'machine learning mathematics',
    ],
    ogImage: '/og/og-ml-variance.png',
  },
  'gradient-descent': {
    title:
      'Gradient Descent Optimization Algorithm - Learning Rate & Momentum | Interactive 3D Visualization',
    description:
      'Master gradient descent optimization with interactive 3D visualization. Explore learning rate impact, momentum acceleration, and convergence behavior. Watch the optimizer navigate loss landscapes, find global minima, and understand batch vs stochastic gradient descent with step-by-step parameter updates.',
    keywords: [
      'gradient descent',
      'gradient descent algorithm',
      'optimization algorithm',
      'machine learning optimization',
      'learning rate',
      'momentum',
      'stochastic gradient descent',
      'SGD',
      'batch gradient descent',
      'mini-batch gradient descent',
      'gradient descent visualization',
      'convex optimization',
      'non-convex optimization',
      'loss function',
      'cost function',
      'parameter optimization',
      'weight update',
      'convergence',
      'local minima',
      'global minima',
      'saddle points',
      'gradient vector',
      'learning rate decay',
      'adaptive learning rate',
      'optimization landscape',
      '3D visualization',
      'interactive optimization',
      'machine learning',
      'ML algorithms',
      'deep learning optimization',
      'neural network training',
      'gradient descent tutorial',
    ],
    ogImage: '/og/og-ml-gradient-descent.png',
  },
  'minmax-scaler': {
    title: 'MinMax Scaler - Feature Scaling & Normalization [0,1] | Interactive Visualization',
    description:
      'Master MinMax scaling for feature normalization with interactive visualization. Scale features to fixed range [0,1] using min-max normalization formula. See before/after transformation, understand when to use MinMax vs Standard scaling, and explore impact on machine learning model performance with step-by-step examples.',
    keywords: [
      'minmax scaler',
      'min-max scaler',
      'feature scaling',
      'data normalization',
      'feature normalization',
      'min-max normalization',
      'rescaling',
      'range normalization',
      '0-1 scaling',
      'data preprocessing',
      'machine learning preprocessing',
      'feature engineering',
      'data transformation',
      'sklearn minmax scaler',
      'normalization techniques',
      'scaling methods',
      'feature range',
      'bounded scaling',
      'ML preprocessing',
      'data science preprocessing',
      'MinMax scaler tutorial',
      'interactive scaler',
      'scaling visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-minmax-scaler.png',
  },
  'standard-scaler': {
    title: 'Standard Scaler - Z-Score Standardization & Normalization | Interactive Visualization',
    description:
      'Master standard scaling (z-score normalization) with interactive visualization. Remove mean and scale to unit variance for optimal machine learning performance. Understand standardization vs normalization, explore Gaussian distribution transformation, and see real-time impact on feature distributions with step-by-step examples.',
    keywords: [
      'standard scaler',
      'standardization',
      'z-score normalization',
      'z-score standardization',
      'feature standardization',
      'mean normalization',
      'unit variance',
      'zero mean',
      'data preprocessing',
      'machine learning preprocessing',
      'feature engineering',
      'data transformation',
      'sklearn standard scaler',
      'gaussian normalization',
      'normal distribution',
      'standardization techniques',
      'scaling methods',
      'standard deviation scaling',
      'ML preprocessing',
      'data science preprocessing',
      'standard scaler tutorial',
      'interactive scaler',
      'standardization visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-standard-scaler.png',
  },
  'linear-regression': {
    title:
      'Linear Regression with Gradient Descent - Least Squares Method | Interactive Visualization',
    description:
      'Master linear regression with gradient descent optimization through interactive 2D visualization. Watch loss function decrease, observe weight and bias updates, and see prediction line fit to data in real-time. Explore ordinary least squares (OLS), cost function minimization, and step-by-step gradient descent iterations for supervised learning.',
    keywords: [
      'linear regression',
      'linear regression algorithm',
      'gradient descent',
      'ordinary least squares',
      'OLS',
      'least squares method',
      'supervised learning',
      'regression algorithm',
      'cost function',
      'loss function',
      'mean squared error',
      'MSE',
      'weight updates',
      'bias term',
      'prediction line',
      'best fit line',
      'regression line',
      'simple linear regression',
      'univariate regression',
      'machine learning regression',
      'predictive modeling',
      'regression analysis',
      'linear model',
      'ML regression',
      'linear regression tutorial',
      'interactive regression',
      'regression visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-linear-regression.png',
  },
  'polynomial-regression': {
    title:
      'Polynomial Regression - Non-Linear Curve Fitting with Gradient Descent | Interactive Visualization',
    description:
      'Master polynomial regression for non-linear curve fitting with interactive visualization. Explore polynomial features, adjust degree (quadratic, cubic), and watch gradient descent optimize coefficients. Understand overfitting vs underfitting, feature transformation, and when to use polynomial regression for complex data patterns.',
    keywords: [
      'polynomial regression',
      'polynomial regression algorithm',
      'curve fitting',
      'non-linear regression',
      'polynomial features',
      'polynomial degree',
      'quadratic regression',
      'cubic regression',
      'feature transformation',
      'regression algorithm',
      'supervised learning',
      'overfitting',
      'underfitting',
      'model complexity',
      'polynomial curve',
      'non-linear relationships',
      'gradient descent',
      'coefficient optimization',
      'regression analysis',
      'machine learning regression',
      'ML regression',
      'polynomial regression tutorial',
      'interactive regression',
      'regression visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-polynomial-regression.png',
  },
  'logistic-regression': {
    title:
      'Logistic Regression - Binary Classification with Sigmoid Function | Interactive Visualization',
    description:
      'Master logistic regression for binary classification with interactive visualization. Explore sigmoid activation function, decision boundary formation, and gradient descent optimization. Watch probability predictions, understand log-loss function, and see real-time classification with step-by-step training iterations for supervised learning.',
    keywords: [
      'logistic regression',
      'logistic regression algorithm',
      'binary classification',
      'sigmoid function',
      'logistic function',
      'activation function',
      'classification algorithm',
      'supervised learning',
      'decision boundary',
      'probability prediction',
      'log-loss',
      'cross-entropy loss',
      'gradient descent',
      'classification threshold',
      'binary classifier',
      'logit function',
      'odds ratio',
      'maximum likelihood',
      'machine learning classification',
      'ML classification',
      'logistic regression tutorial',
      'interactive classification',
      'classification visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-logistic-regression.png',
  },
  'anomaly-detection': {
    title: 'Anomaly Detection Algorithms',
    description:
      'Explore anomaly detection methods including Isolation Forest, One-Class SVM, Local Outlier Factor, and statistical approaches. Identify outliers in your data with interactive visualizations.',
    keywords: [
      'anomaly detection',
      'outlier detection',
      'isolation forest',
      'one class svm',
      'local outlier factor',
      'lof',
      'z score',
      'iqr method',
      'novelty detection',
      'unsupervised learning',
      'machine learning',
      'data mining',
      'interactive visualization',
      'algorithm comparison',
    ],
    ogImage: '/og/og-ml-anomaly-detection.png',
  },
  'decision-tree': {
    title:
      'Decision Tree Classifier - CART Algorithm with Gini Impurity | Interactive Visualization',
    description:
      'Master decision tree classification with interactive CART (Classification and Regression Trees) visualization. Explore Gini impurity, information gain, and entropy measures. Watch recursive binary splitting build decision boundaries, understand pruning techniques, and see step-by-step tree construction for multi-class classification problems.',
    keywords: [
      'decision tree',
      'decision tree classifier',
      'decision tree algorithm',
      'CART algorithm',
      'classification tree',
      'classification and regression trees',
      'gini impurity',
      'gini index',
      'information gain',
      'entropy',
      'recursive partitioning',
      'binary splitting',
      'decision nodes',
      'leaf nodes',
      'tree pruning',
      'max depth',
      'min samples split',
      'feature importance',
      'decision boundary',
      'tree visualization',
      'supervised learning',
      'multi-class classification',
      'machine learning classification',
      'ML classification',
      'decision tree tutorial',
      'interactive tree',
      'tree-based learning',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-decision-tree.png',
  },
  'ensemble-models': {
    title: 'Random Forest & Ensemble Learning - Bagging & Boosting | Interactive Visualization',
    description:
      'Master ensemble learning with Random Forest interactive visualization. Explore bagging, boosting, and voting techniques. Watch multiple decision trees combine predictions through majority voting, understand feature randomness, out-of-bag error, and see how ensemble methods achieve superior accuracy and reduce overfitting.',
    keywords: [
      'random forest',
      'random forest classifier',
      'ensemble learning',
      'ensemble methods',
      'bagging',
      'bootstrap aggregating',
      'boosting',
      'ensemble models',
      'decision trees',
      'voting classifier',
      'majority voting',
      'feature randomness',
      'feature bagging',
      'out-of-bag error',
      'OOB error',
      'feature importance',
      'model aggregation',
      'bias-variance tradeoff',
      'overfitting reduction',
      'robust classification',
      'supervised learning',
      'machine learning ensemble',
      'ML ensemble',
      'random forest tutorial',
      'interactive ensemble',
      'ensemble visualization',
      'machine learning',
      'ML',
    ],
    ogImage: '/og/og-ml-ensemble-models.png',
  },
  'k-means': {
    title:
      'K-Means & K-Means++ Clustering Algorithm - Interactive 3D Visualization | Unsupervised ML',
    description:
      'Master K-Means and K-Means++ clustering with interactive 3D visualization. Compare initialization methods, watch centroids converge in real-time, explore the elbow method for optimal k selection, and visualize clustering in 2D/3D space. Step-by-step algorithm walkthrough with centroid trajectories and cluster assignments.',
    keywords: [
      'k-means clustering',
      'k-means++ algorithm',
      'kmeans++ initialization',
      'unsupervised learning',
      'clustering algorithm',
      'centroid-based clustering',
      'elbow method',
      'machine learning clustering',
      'ML',
      'interactive clustering',
      '3D clustering visualization',
      'centroid convergence',
      'cluster analysis',
      'data clustering',
      'unsupervised machine learning',
      'k-means tutorial',
      'clustering playground',
      'algorithm visualization',
      'machine learning algorithms',
      'data science',
      'centroid trajectories',
      'cluster centroids',
    ],
    ogImage: '/og/og-ml-k-means.png',
  },
  gmm: {
    title: 'Gaussian Mixture Model (GMM) - EM Algorithm Visualization | Interactive Clustering',
    description:
      'Master Gaussian Mixture Models with step-by-step EM algorithm visualization. Watch E-step compute responsibilities, M-step update parameters, and explore soft clustering with covariance ellipses. Interactive playground with K-Means++ initialization, convergence tracking, and probabilistic cluster assignments.',
    keywords: [
      'gaussian mixture model',
      'GMM clustering',
      'EM algorithm',
      'expectation maximization',
      'expectation maximization algorithm',
      'soft clustering',
      'probabilistic clustering',
      'gaussian components',
      'multivariate gaussian',
      'covariance matrix',
      'covariance ellipses',
      'E-step M-step',
      'responsibility assignment',
      'mixture weights',
      'unsupervised learning',
      'model-based clustering',
      'K-Means++ initialization',
      'log-likelihood convergence',
      'GMM visualization',
      'clustering algorithm',
      'statistical learning',
      'density estimation',
      'machine learning clustering',
      'ML unsupervised',
      'data science',
      'GMM tutorial',
      'interactive GMM',
    ],
    ogImage: '/og/og-ml-gmm.png',
  },
  dbscan: {
    title: 'DBSCAN Clustering - Density-Based Spatial Clustering | Interactive Visualization',
    description:
      'Master DBSCAN (Density-Based Spatial Clustering of Applications with Noise) with step-by-step visualization. Explore density-based clustering, core points, border points, and noise detection. Interactive playground with epsilon radius adjustment, minPts parameter tuning, and automatic cluster discovery without predefined K.',
    keywords: [
      'DBSCAN clustering',
      'DBSCAN algorithm',
      'density-based clustering',
      'spatial clustering',
      'density clustering',
      'core points',
      'border points',
      'noise detection',
      'outlier detection',
      'epsilon radius',
      'eps parameter',
      'minPts parameter',
      'unsupervised learning',
      'clustering algorithm',
      'arbitrary shaped clusters',
      'no K required',
      'neighborhood search',
      'reachability distance',
      'DBSCAN visualization',
      'interactive DBSCAN',
      'machine learning clustering',
      'ML unsupervised',
      'data science',
      'anomaly detection',
      'DBSCAN tutorial',
      'density estimation',
    ],
    ogImage: '/og/og-ml-dbscan.png',
  },
  'hierarchical-clustering': {
    title: 'Hierarchical Clustering - Agglomerative Clustering | Interactive Visualization',
    description:
      'Master Hierarchical Clustering with step-by-step visualization. Explore agglomerative (bottom-up) clustering, linkage methods (single, complete, average), and dendrogram construction. Interactive playground with dynamic cluster merging, distance matrix visualization, and target cluster selection.',
    keywords: [
      'hierarchical clustering',
      'agglomerative clustering',
      'divisive clustering',
      'dendrogram',
      'linkage methods',
      'single linkage',
      'complete linkage',
      'average linkage',
      'bottom-up clustering',
      'top-down clustering',
      'distance matrix',
      'cluster merging',
      'unsupervised learning',
      'clustering algorithm',
      'hierarchical structure',
      'cluster hierarchy',
      'ward linkage',
      'centroid linkage',
      'hierarchical visualization',
      'interactive clustering',
      'machine learning clustering',
      'ML unsupervised',
      'data science',
      'cluster analysis',
      'hierarchical tutorial',
      'taxonomic classification',
    ],
    ogImage: '/og/og-ml-hierarchical-clustering.png',
  },
  knn: {
    title: 'K-Nearest Neighbors (KNN) Algorithm',
    description:
      'Master K-Nearest Neighbors (KNN) with step-by-step interactive visualization. Explore distance metrics (Euclidean, Manhattan), k-value selection, decision boundaries, and weighted voting. Interactive playground with real-time classification, distance visualization, and neighbor highlighting for supervised learning.',
    keywords: [
      'k-nearest neighbors',
      'KNN algorithm',
      'KNN classification',
      'KNN regression',
      'nearest neighbors',
      'instance-based learning',
      'lazy learning',
      'distance metrics',
      'euclidean distance',
      'manhattan distance',
      'minkowski distance',
      'k-value selection',
      'decision boundary',
      'weighted voting',
      'uniform weights',
      'distance weights',
      'classification algorithm',
      'supervised learning',
      'non-parametric algorithm',
      'pattern recognition',
      'neighbor search',
      'KNN visualization',
      'interactive KNN',
      'machine learning classification',
      'ML supervised',
      'data science',
      'KNN tutorial',
      'distance-based classification',
    ],
    ogImage: '/og/og-ml-knn.png',
  },
}

export type MLRoute = keyof typeof mlMetadata

// Helper function to generate metadata for ML pages
export function generateMLMetadata(route: MLRoute, customAlt?: string) {
  const meta = mlMetadata[route]
  const baseUrl = 'https://www.learn-algo.com'
  const canonicalUrl = `${baseUrl}/ml/${route}`

  return {
    title: meta.title,
    description: meta.description,
    keywords: meta.keywords,
    authors: [{ name: 'LEARN ALGO' }],
    creator: 'LEARN ALGO',
    publisher: 'LEARN ALGO',
    alternates: {
      canonical: canonicalUrl,
    },
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large' as const,
        'max-snippet': -1,
      },
    },
    openGraph: {
      title: `${meta.title} | Learn Algo`,
      description: meta.description,
      type: 'article' as const,
      url: canonicalUrl,
      siteName: 'LEARN ALGO',
      locale: 'en_US',
      images: [
        {
          url: `${baseUrl}${meta.ogImage}`,
          width: 1200,
          height: 630,
          alt: customAlt || `${meta.title} Visualization`,
          type: 'image/png',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image' as const,
      title: `${meta.title} | Learn Algo`,
      description: meta.description,
      site: '@LearnAlgo',
      creator: '@LearnAlgo',
      images: [`${baseUrl}${meta.ogImage}`],
    },
  }
}

// Helper function to generate structured data (JSON-LD) for ML algorithm pages
export function generateMLStructuredData(route: MLRoute) {
  const meta = mlMetadata[route]
  const baseUrl = 'https://www.learn-algo.com'
  const canonicalUrl = `${baseUrl}/ml/${route}`

  // Get algorithm category
  const getAlgorithmCategory = (keywords: string[]) => {
    if (keywords.includes('regression algorithm')) return 'Regression Algorithm'
    if (keywords.includes('classification algorithm')) return 'Classification Algorithm'
    if (keywords.includes('clustering algorithm')) return 'Clustering Algorithm'
    if (keywords.includes('data preprocessing')) return 'Data Preprocessing'
    if (keywords.includes('optimization algorithm')) return 'Optimization Algorithm'
    return 'Machine Learning Algorithm'
  }

  return {
    '@context': 'https://schema.org',
    '@type': 'TechArticle',
    headline: meta.title,
    description: meta.description,
    url: canonicalUrl,
    image: `${baseUrl}${meta.ogImage}`,
    author: {
      '@type': 'Organization',
      name: 'LEARN ALGO',
      url: baseUrl,
    },
    publisher: {
      '@type': 'Organization',
      name: 'LEARN ALGO',
      url: baseUrl,
      logo: {
        '@type': 'ImageObject',
        url: `${baseUrl}/logo/logo.png`,
      },
    },
    datePublished: '2025-01-01',
    dateModified: new Date().toISOString().split('T')[0],
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': canonicalUrl,
    },
    articleSection: getAlgorithmCategory(meta.keywords),
    keywords: meta.keywords.join(', '),
    educationalLevel: 'Beginner to Advanced',
    learningResourceType: 'Interactive Visualization',
    interactivityType: 'active',
    about: {
      '@type': 'Thing',
      name: meta.title,
      description: meta.description,
    },
    teaches: meta.title,
  }
}
