export { LinearRegressionPlayground } from './LinearRegressionPlayground'
export { LogisticRegressionPlayground } from './LogisticRegressionPlayground'
export { KMeansClusteringPlayground } from './KMeansClusteringPlayground'
export { GradientDescentPlayground } from './GradientDescentPlayground'
export { PolynomialRegressionPlayground } from './PolynomialRegressionPlayground'
export { KNNPlayground } from './KNNPlayground'
